___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [60]:
import numpy as np

#### Create an array of 10 zeros 

In [61]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [62]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [63]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [64]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [65]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [66]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [67]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [68]:
np.random.rand()

0.28415712604799015

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [69]:
np.random.randn(25)

array([ 0.48496709, -0.02973969, -0.97889288, -1.21280655,  0.35995235,
       -1.53724962, -1.50270178,  0.07147782,  0.24997603,  0.1550579 ,
        0.57079465,  0.54321427,  0.49988017, -0.5802497 , -0.28364721,
       -2.00156765,  0.40033672,  1.31067838, -0.94882322,  1.35807522,
        0.58120353, -1.06368667,  0.48133784, -0.43998425, -0.67853721])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [70]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [71]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [72]:
# [[12, 13, 14, 15], 
# [17, 18, 19, 20],
# [22, 23, 24, 25]]

mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [73]:
# 20

mat[3, 4]

np.int64(20)

In [74]:
# [[ 2], [ 7], [12]]

mat[:3,1]

array([ 2,  7, 12])

In [75]:
# [21, 22, 23, 24, 25]

mat[4]

array([21, 22, 23, 24, 25])

In [76]:
# [[16, 17, 18, 19, 20],
# [21, 22, 23, 24, 25]]

mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [77]:
mat.sum()

np.int64(325)

#### Get the standard deviation of the values in mat

In [78]:
mat.std()

np.float64(7.211102550927978)

#### Get the sum of all the columns in mat

In [79]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

# Great Job!